Algoritmo "semnome"
// Disciplina  : Lógica de Programação I 
// Professor   : Rogério Alexandre 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/03/2017
Var
// Seção de Declarações das variáveis 
   contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para contador de 1000 ate 5000 faca
    escreval (contador)
    fimpara
Fimalgoritmo