algoritmo "exercicioprocedimento2"
var
   n: inteiro
   procedimento quadrado(x : inteiro)
   var
      i: inteiro
   inicio
         para i de 1 ate x faca
              escreval
              para i de 1 ate x faca
                   escreva ("* ")
              fimpara
         fimpara
   fimprocedimento
inicio
      escreva ("Digite um número: ")
              leia (n)
      quadrado(n)
fimalgoritmo
   
   